name: Lint

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Check Format
        run: bun fmt:check

      - name: Lint
        run: bun lint
